### ISSUE TITLE
go vet API support

### ISSUE THREAD

**Issue by nikolaydubina** [uudashr/gocognit#16]
Would be great if this tool supported `go vet` API, so that it can be integrated with standard Go  vet toolchain.

https://pkg.go.dev/golang.org/x/tools/go/analysis

Example:
- github.com/jlauinger/go-safer

**Comment by uudashr** [comment]
Can you explain more?
Gocognit provide Analyzer https://pkg.go.dev/github.com/uudashr/gocognit#pkg-variables that can be used as an API.
Let me know whether it sufficient? or maybe you can explain more detailed requirement

**Comment by nikolaydubina** [comment]
yeah, I don't know why I missed that. false alarm !
