### ISSUE TITLE
Value is not so meaningful for go code

### ISSUE THREAD

**Issue by igorfraa** [uudashr/gocognit#4]
in GoLang, we have a wast amount of `if err != nil {}`.

let's consider a following example:
```go
if _, err := strconv.ParseFloat(value, 64) ; err != nil {
  return err
}
```

There could be a dozen of similar statements in a function, each adding two points to a computed complexity value. 

These if's add no complexity - modern IDE's even collapse these lines due there is nothing of interest.

It seems the tool should ignore such lines.

**Comment by uudashr** [comment]
Well, generally "conditional" will increase the cognitive load.

Modern IDE has a way to help us to understand this and collapse the lines. Reading source code is not always on modern IDE. People might want to review the code just by seeing the text without fancy tools.
