### ISSUE TITLE
Evaulate `goto` end practices

### ISSUE THREAD

**Issue by hollowaykeanho** [uudashr/gocognit#5]
For `goto` end practices, `gocognit` is not able to evaluate properly for the following case:

```
// Generate is to create all the debian / DEBIAN files and directories.
func (me *Data) Generate(workingDir string) (err error) {
	var path string

	err = me.Sanitize()
	if err != nil {
		goto done
	}

	if workingDir == "" {
		err = fmt.Errorf("%s: workingDir = ''", ERROR_DIR_MISSING)
		goto done
	}

	// identify debian or DEBIAN directory by Control/BuildSource.
	if me.Control.BuildSource {
		path = filepath.Join(workingDir, "debian")
	} else {
		path = filepath.Join(workingDir, "DEBIAN")
	}

	err = me.createBaseDir(path)
	if err != nil {
		goto done
	}

	err = me.createControl(path)
	if err != nil {
		goto done
	}

	err = me.createCopyright(path)
	if err != nil {
		goto done
	}

	err = me.createChangelog(path)
	if err != nil {
		goto done
	}

	err = me.createSourceDir(path)
	if err != nil {
		goto done
	}

	err = me.writeSourceFormat(path)
	if err != nil {
		goto done
	}

	err = me.writeSourceLocalOptions(path)
	if err != nil {
		goto done
	}

	err = me.writeSourceOptions(path)
	if err != nil {
		goto done
	}

	err = me.writeManpages(path)
	if err != nil {
		goto done
	}

	err = me.writeScripts(path)
	if err != nil {
		goto done
	}

	err = me.writeRules(path)
	if err != nil {
		goto done
	}

	err = me.writeCompat(path)
	if err != nil {
		goto done
	}

	err = me.writeInstall(path)
	if err != nil {
		goto done
	}

done:
	return err
}
```
Will dump:
```
monteur/internal/archive/deb/Data.go:102:1: cognitive complexity 32 of func `(*Data).Generate` is hi
gh (> 20) (gocognit)
```

If switching the practice back to `return` everytime, gocognit seems okay. 

Note that this "uni-direction" jump is a practice (adopted from https://www.kernel.org/doc/html/v4.17/process/coding-style.html#centralized-exiting-of-functions, specifically designed for clean-up (e.g. programatically closing files when `defer` is not suitable.

---

In case any zealot of anti-`goto`: it's fine to use `goto` for a single direction flow especially for clean up as long as it is not abused for structural programming replacement.

For most cases: http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html

**Comment by uudashr** [comment]
Hi there, `gocognit` is developed based on [Cognitive Complexity whitepaper](https://www.sonarsource.com/docs/CognitiveComplexity.pdf).

I do agree we can use `goto` for the centralized exit. In my understanding, this is only one use case, but not always. Generally using `goto` can make the code harder to understand.

Using `return` is straightforward. Using `goto label` will depend on the use case

**Comment by hollowaykeanho** [comment]
> I do agree we can use `goto` for the centralized exit. In my understanding, this is only one use case, but not always.

From 8 years of past experiences, this is **the only `goto` use case** ><. Anything else is a complete nightmare. 

> gocognit is developed based on Cognitive Complexity whitepaper.

Yeap. That's why I enjoyed `gocognit` over `gocyclo`. I'll post more snippets over this week from my current OSI project so that you have better supporting cases.

**Comment by uudashr** [comment]
I'm closing this issue. Please re-open if you have something more to discuss
